### ISSUE TITLE
Replace absolute numbers in Stackoverflow by percentages

### ISSUE THREAD

**Issue by Riduidel** [Zenika/tendances-et-opportunites#30]
Why ?
StackOverflow popularity is lowering since 2017. As a consequence, all popularities are doing the same move, which is not so representative.
We should find a way to isolate our tags popularities from StackOverflow one. The most typical one could be to replace absolute number of questions/answers by relative ones (so, going to percentages woul be a better solution). 

More formally, for each tag, on questions and answers, can we add beside the absolute popularity a relative popularity computed by "number of elements for the given tag this month/total number of element this month".
Obviously, the sum of percentages won't reach 100%, because one question can have more than one tag. But this could allow us to mitigate the popularity loss of StackOverflow.

**Comment by rlemaire** [comment]
Percentage implies a closed set of tags (30% for java, 30% of what ?).
You can use a number that is corrected with a coefficient
